### Importing Necessary Libraries

In [2]:
import pandas as pd
import numpy as np

### Importing the Dataset Reqired for the Task

In [3]:
df=pd.read_csv(r"C:\Users\SHREE\Downloads\Python CODES\Nearest Pub Mapping using Latitude and Longitude\open_pubs.csv",
               header=None, keep_default_na=False)
df.head()

0                   1                                                  2  \
0  22          Anchor Inn        Upper Street, Stratford St Mary, COLCHESTER   
1  36  Ark Bar Restaurant  Ark Bar And Restaurant, Cattawade Street, Bran...   
2  74           Black Boy  The Lady Elizabeth, 7 Market Hill, SUDBURY, Su...   
3  75         Black Horse        Lower Street, Stratford St Mary, COLCHESTER   
4  76          Black Lion                      Lion Road, Glemsford, SUDBURY   

          3       4        5          6         7        8  
0   CO7 6LW  604749   234404  51.970379  0.979340  Babergh  
1  CO11 1RH  610194   233329  51.958698  1.057832  Babergh  
2  CO10 2EA  587334   241316  52.038595  0.729915  Babergh  
3   CO7 6JS  622675 -5527598         \N        \N  Babergh  
4  CO10 7RF  622675 -5527598         \N        \N  Babergh

### Adding Names to the Columns

In [4]:
df.columns=['fsa_id','name','address','postcode','easting','northing','latitude','longitude','local_authority']
df.head()

fsa_id                name  \
0      22          Anchor Inn   
1      36  Ark Bar Restaurant   
2      74           Black Boy   
3      75         Black Horse   
4      76          Black Lion   

                                             address  postcode  easting  \
0        Upper Street, Stratford St Mary, COLCHESTER   CO7 6LW   604749   
1  Ark Bar And Restaurant, Cattawade Street, Bran...  CO11 1RH   610194   
2  The Lady Elizabeth, 7 Market Hill, SUDBURY, Su...  CO10 2EA   587334   
3        Lower Street, Stratford St Mary, COLCHESTER   CO7 6JS   622675   
4                      Lion Road, Glemsford, SUDBURY  CO10 7RF   622675   

   northing   latitude longitude local_authority  
0    234404  51.970379  0.979340         Babergh  
1    233329  51.958698  1.057832         Babergh  
2    241316  52.038595  0.729915         Babergh  
3  -5527598         \N        \N         Babergh  
4  -5527598         \N        \N         Babergh

### Understanding the Dataset

In [5]:
df.shape

(51331, 9)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51331 entries, 0 to 51330
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   fsa_id           51331 non-null  int64 
 1   name             51331 non-null  object
 2   address          51331 non-null  object
 3   postcode         51331 non-null  object
 4   easting          51331 non-null  int64 
 5   northing         51331 non-null  int64 
 6   latitude         51331 non-null  object
 7   longitude        51331 non-null  object
 8   local_authority  51331 non-null  object
dtypes: int64(3), object(6)
memory usage: 3.5+ MB


In [7]:
df.isna().sum()

fsa_id             0
name               0
address            0
postcode           0
easting            0
northing           0
latitude           0
longitude          0
local_authority    0
dtype: int64

### There are missing value and are named as \N. 
- Checking how many such rows we have in our dataset and removing those rows.

In [9]:
# Creating a function for checking "\N" values $ Replacing them with "nan"

def change_N_to_nan(col_val):
    if col_val==r'\N':
        return np.nan
    else:
        return col_val

df['fsa_id']=df['fsa_id'].apply(change_N_to_nan)
df['name']=df['name'].apply(change_N_to_nan)
df['address']=df['address'].apply(change_N_to_nan)
df['postcode']=df['postcode'].apply(change_N_to_nan)
df['easting']=df['easting'].apply(change_N_to_nan)
df['northing']=df['northing'].apply(change_N_to_nan)
df['latitude']=df['latitude'].apply(change_N_to_nan)
df['longitude']=df['longitude'].apply(change_N_to_nan)
df['local_authority']=df['local_authority'].apply(change_N_to_nan)

In [10]:
df.isna().sum()

fsa_id               0
name                 0
address              0
postcode             0
easting              0
northing             0
latitude           767
longitude          767
local_authority      0
dtype: int64

In [11]:
# Droping the "nan" values

df.dropna(axis=0, inplace=True)
df.isna().sum()

fsa_id             0
name               0
address            0
postcode           0
easting            0
northing           0
latitude           0
longitude          0
local_authority    0
dtype: int64

### Changing the Datatype of Longitude and Latitude to Float

In [12]:
df['longitude']=df['longitude'].astype(float)
df['latitude']=df['latitude'].astype(float)

In [13]:
df.dtypes

fsa_id               int64
name                object
address             object
postcode            object
easting              int64
northing             int64
latitude           float64
longitude          float64
local_authority     object
dtype: object

### Total Pub

In [14]:
df['name'].nunique()

35809

### Total Local Authorities

In [15]:
df['local_authority'].nunique()

360

### Clean Dataset

In [16]:
df.to_csv(r"C:\Users\SHREE\Downloads\Python CODES\Nearest Pub Mapping using Latitude and Longitude\open_pubs.csv", index=False)

### Nearby Pubs Mapping by latitude and longitude

In [17]:
points=np.array((float(input()),float(input())))
points

51.970388
1.057536


array([51.970388,  1.057536])

### Convert latitude and longitude to array

In [18]:
arr=np.array([df['latitude'],df['longitude']]).T
arr

array([[51.970379,  0.97934 ],
       [51.958698,  1.057832],
       [52.038595,  0.729915],
       ...,
       [53.044998, -2.996966],
       [53.053094, -2.959124],
       [53.076638, -3.050512]])

### Calculating Distance between the given Latitude & Longitude

In [19]:
dis=np.sum((arr-points)**2, axis=1)
dis

array([6.11461450e-03, 1.36743716e-04, 1.11987714e-01, ...,
       1.75937731e+01, 1.73058098e+01, 1.80998474e+01])

In [20]:
df['Distance']=dis

## 5 Nearest Pub Locations

In [21]:
df.sort_values(by='Distance', ascending=True)[:5]

fsa_id                name  \
29       591           Royal Oak   
60       797          The Grange   
1         36  Ark Bar Restaurant   
52       775       The Crown Inn   
3987   47315       Skinners Arms   

                                                address  postcode  easting  \
29    Royal Oak, East End Lane, East Bergholt, COLCH...   CO7 6XA   609998   
60    The Grange Country Park, Straight Road, East B...   CO7 6UX   609841   
1     Ark Bar And Restaurant, Cattawade Street, Bran...  CO11 1RH   610194   
52    Crown Inn, Cattawade Street, Brantham, MANNING...  CO11 1RE   610209   
3987                       Station Road, Lawford, Essex  CO11 1DX   610493   

      northing   latitude  longitude local_authority  Distance  
29      235171  51.975311   1.056110         Babergh  0.000026  
60      235186  51.975506   1.053837         Babergh  0.000040  
1       233329  51.958698   1.057832         Babergh  0.000137  
52      233104  51.956673   1.057912         Babergh  0.000188  
3987    231873  51.945514   1.061287        Tendring  0.000633